const themes = [
  {
    '--keyboard-color': '#b08fbb',
    '--keyboard-shadow-color': '#825d8e',
    '--standard-color': '#f6d5d5',
    '--standard-shadow-color': '#9b7474',
    '--standard-hover-color': '#dfafaf',
    '--standard-text-color': '#8d6565',
    '--nav-color': '#ca498c',
    '--nav-shadow-color': '#9a3d6d',
    '--nav-hover-color': '#ac4d7e',
    '--nav-text-color': '#f7d5d5',
    '--uniq-color': '#8b2f8a',
    '--uniq-shadow-color': '#5b2d5b',
    '--uniq-hover-color': '#5a1a5a',
    '--uniq-text-color': '#e1d6e1',
  },
  {
    '--keyboard-color': '#ffd3b6',
    '--keyboard-shadow-color': '#af917d',
    '--standard-color': '#ffaaa5',
    '--standard-shadow-color': '#aa706d',
    '--standard-hover-color': '#fa968e',
    '--standard-text-color': '#885450',
    '--nav-color': '#dcedc1',
    '--nav-shadow-color': '#77885d',
    '--nav-hover-color': '#a3b982',
    '--nav-text-color': '#6b7c50',
    '--uniq-color': '#a8e6cf',
    '--uniq-shadow-color': '#648f7f',
    '--uniq-hover-color': '#87c0ab',
    '--uniq-text-color': '#065a3b',
  },
  {
    '--keyboard-color': '#eaeaea',
    '--keyboard-shadow-color': '#c8c8c8',
    '--standard-color': '#a1dd70',
    '--standard-shadow-color': '#618643',
    '--standard-hover-color': '#84bc55',
    '--standard-text-color': '#425f2a',
    '--nav-color': '#8559a5',
    '--nav-shadow-color': '#4d2b66',
    '--nav-hover-color': '#724591',
    '--nav-text-color': '#43205d',
    '--uniq-color': '#00bdaa',
    '--uniq-shadow-color': '#185b55',
    '--uniq-hover-color': '#0b9587',
    '--uniq-text-color': '#185b55',
  },
];

export default themes;
